Add NamibLII law reform menu item
laws-africa/peachjam pull request #1134
Opened 2023-04-26 17:21 UTC by nickmwangemi

![image](https://user-images.githubusercontent.com/15012985/234653514-c2eea24e-1fed-499e-a7a6-919ed80d8b96.png)

![image](https://user-images.githubusercontent.com/15012985/234653776-098ba284-010e-4441-8e2b-e4e6cf38421e.png)

2023-04-27 05:20 UTC, longhotsummer reviewed
Good start, needs some tweaks.

2023-04-27 05:20 UTC, longhotsummer commented on namiblii/templates/peachjam/_header.html
> +    {% with namiblii_law_reform_author as pk %}
You don't need the with block since you only use the custom template tag once.

2023-04-27 05:20 UTC, longhotsummer commented on namiblii/templatetags/namiblii.py
> +    author = get_object_or_404(Author, code="NALRDC")
This will cause every page on the site to 404 if that author doesn't exist, which will be hard to debug. Instead, return None.

2023-04-28 08:18 UTC, actlikewill requested changes

2023-04-28 08:18 UTC, actlikewill commented on peachjam/urls.py
> +        "authors/<str:code>/",
```suggestion
        "authors/<slug:code>/",
```

2023-04-28 08:18 UTC, actlikewill commented on namiblii/templates/peachjam/_header.html
> +{% load namiblii i18n %}
```suggestion
{% load i18n %}
```

2023-04-28 08:18 UTC, actlikewill commented on namiblii/templates/peachjam/_header.html
> +       href="{% 'author' 'NALRDC' %}">
```suggestion
       href="{% url 'author' 'NALRDC' %}">
```

2023-04-28 08:35 UTC, actlikewill approved these changes
looks good

2023-04-28 08:58 UTC, merged