Home page logos
laws-africa/peachjam pull request #1210
Opened 2023-05-16 14:40 UTC by actlikewill

- Change to homepage layout
closes #1116

![image](https://github.com/laws-africa/peachjam/assets/25079238/6b234c89-3640-46be-b13d-5078e208561a)

![image](https://github.com/laws-africa/peachjam/assets/25079238/343d3e88-3595-4a65-aec9-eaf927e48ce6)

![image](https://github.com/laws-africa/peachjam/assets/25079238/25803502-2c53-4015-bc8d-096a59529b77)

2023-05-16 15:21 UTC, longhotsummer requested changes
Looks great.

I pushed a small change in https://github.com/laws-africa/peachjam/pull/1210/commits/5daed75923a28036073368e8c47eb3ec6cd207eb which fixes lack of containers and makes the hero logos work better on mobile. It also makes them much easier to code in the first place.

I've updated lawlibrary but the others must be updated.

2023-05-17 02:27 UTC, actlikewill commented
@longhotsummer Updatesd. Looks much better.

2023-05-17 06:16 UTC, nickmwangemi approved these changes

2023-05-17 06:43 UTC, longhotsummer approved these changes
great

2023-05-17 06:44 UTC, merged