Brand Open Law Africa sites
laws-africa/peachjam pull request #1514
Opened 2023-09-07 13:01 UTC by nickmwangemi

2023-09-07 14:13 UTC, actlikewill commented
@nickmwangemi I think you can have single image in the base peachjam static folder instead of separate ones in each lii

2023-09-07 14:40 UTC, longhotsummer commented on ulii/static/images/open-law-africa-footer.png
just add the images once, in the `liiweb` project.

2023-09-07 14:40 UTC, longhotsummer commented on ulii/static/images/open-law-africa-footer.png
actually, `peachjam` makes more sense.

2023-09-08 07:30 UTC, longhotsummer requested changes
In general this looks good, but we need a few changes:

1. right-align the OLA logo in the headers
2. when right-aligned, the images shouldn't have `class="me-4"` because that puts margin on the right, which is not necessary
3. we'll need to do something on africanlii because on mobile the images are too wide.

The footer stuff looks good.

2023-09-08 09:58 UTC, longhotsummer requested changes
I've adjusted widths on mobile and removed the need for specific heights.

The OLA logos are still duplicated between liiweb and peachjam. They can move into peachjam. I think we only need two: the normal and the inverted.

Please also check with @actlikewill how to reduce them down to a decent size -- 256KB is pretty large.

2023-09-11 10:56 UTC, longhotsummer approved these changes

2023-09-12 06:03 UTC, merged