basic user profile page
laws-africa/peachjam pull request #2091
Opened 2024-10-08 11:50 UTC by Sandravaphilips

Closes #2035 
<img width="1222" alt="Screenshot 2024-10-08 at 12 47 13" src="https://github.com/user-attachments/assets/5ce57997-416a-4009-bc2a-699d9f47e71b">
<img width="1160" alt="Screenshot 2024-10-08 at 12 47 22" src="https://github.com/user-attachments/assets/4d57f8dc-a0ce-4c77-87be-d7dbdf17a438">
<img width="1194" alt="Screenshot 2024-10-08 at 12 47 31" src="https://github.com/user-attachments/assets/19800248-d9dd-4a30-a657-24399d70fc24">
<img width="1206" alt="Screenshot 2024-10-08 at 12 47 40" src="https://github.com/user-attachments/assets/2cfde2d4-5b7e-424e-b369-1116817dcf93">
<img width="1160" alt="Screenshot 2024-10-08 at 12 47 52" src="https://github.com/user-attachments/assets/ef2d9211-20d4-4ee9-b4a7-77976c546485">

2024-10-10 12:31 UTC, longhotsummer commented on peachjam/views/accounts.py
> +        initial = super(EditAccountView, self).get_initial()
I don't think this method is necessary because the form will be initialised from the properties on `get_object`

2024-10-10 12:32 UTC, longhotsummer commented on peachjam/forms.py
> +    first_name = forms.CharField(label=_("First name"))
you should be able to drop both of these and just use what the form determines from the object's properties.

Also the class name would usually be `UserForm`

2024-10-15 10:37 UTC, actlikewill commented on peachjam/templates/account/password_change.html
> +  <form method="post" action="{% url 'account_change_password' %}">
This form and the user name form can be a little smaller, Perhaps half the page instead of the full page.

2024-10-16 09:02 UTC, Sandravaphilips commented
@longhotsummer this is ready

2024-10-16 09:56 UTC, longhotsummer commented on peachjam/templates/account/email.html
> +    <h5 class="card-header">Email addresses</h5>
trans

2024-10-16 09:59 UTC, longhotsummer commented on peachjam/templates/account/password_change.html
> +          <h5 class="card-header">{% trans 'Change Your Password' %}</h5>
Sentence case

2024-10-16 10:00 UTC, longhotsummer commented on peachjam/templates/user_account/layout.html
> +    <h1 class="mb-3 mt-3">{% trans "My Account" %}</h1>
Sentence case

2024-10-16 10:01 UTC, longhotsummer requested changes
Looks good - just translations and sentence casing please

2024-10-16 10:22 UTC, longhotsummer approved these changes

2024-10-16 11:10 UTC, merged