Fetch all points in time from indigo
laws-africa/peachjam pull request #344
Opened 2022-08-26 11:48 UTC by longhotsummer

* fetch all points in time from indigo - closes #342 
* handle stubs from indigo - closes #324 
* stubs must use publication document as source and not store any content_html
* when clearing ingestor dates, queue the background task to update them
* source file downloading: show file type, decent filename
* store attachment sizes in db rather than fetching from storage
* logging

2022-08-30 08:06 UTC, nickmwangemi commented on peachjam/views/documents.py
> +            response = HttpResponse(bytes, content_type=source_file.mimetype)
Assigning to a builtin variable. 
```suggestion
            file_bytes = file.read()
            response = HttpResponse(file_bytes, content_type=source_file.mimetype)
```

2022-08-30 08:07 UTC, nickmwangemi commented on peachjam/views/documents.py
> +            response["Content-Length"] = str(len(bytes))
```suggestion
            response["Content-Length"] = str(len(file_bytes))
```

2022-08-30 08:41 UTC, nickmwangemi requested changes
Tested the changes locally and they work well. Just that one minor change and merge conflict resolution and it should be good to go.

2022-08-30 09:02 UTC, actlikewill approved these changes

2022-08-30 12:42 UTC, longhotsummer commented
> Tested the changes locally and they work well. Just that one minor change and merge conflict resolution and it should be good to go.

Nice catch, thanks. Committed your suggestions.

2022-08-31 07:41 UTC, nickmwangemi approved these changes

2022-08-31 07:41 UTC, merged