Create Article and UserProfile models
laws-africa/peachjam pull request #364
Opened 2022-09-06 12:50 UTC by nickmwangemi

2022-09-07 13:25 UTC, longhotsummer commented
Looking good. I'll wait for the views for a full review :)

2022-09-07 13:25 UTC, longhotsummer commented
Closes https://github.com/laws-africa/peachjam/issues/130

2022-09-08 07:10 UTC, nickmwangemi commented on peachjam/models/article.py
> +    title = models.CharField(max_length=1024, null=False, blank=False)
Done.

2022-09-20 07:38 UTC, longhotsummer reviewed
All of this can live in peachjam. An article is a foundational model which all our sites could make use of.

2022-09-20 07:39 UTC, longhotsummer commented on lawlibrary/templates/lawlibrary/article_detail.html
> +<h1>Article Detail</h1>
These top-level templates can extend the basic peachjam template (main.html I think?) so that they get the basic layout.

2022-09-20 08:42 UTC, longhotsummer commented on peachjam/models/article.py
> +    body = models.TextField()
In the admin view, this should use a ckeditor widget.

2022-09-20 08:45 UTC, longhotsummer commented on peachjam/models/article.py
> +    image = models.ImageField(upload_to="articles/")
As mentioned, we'll need to scope the upload folder based on the pk of the model. See how we do it for BaseAttachment.

2022-09-21 08:40 UTC, longhotsummer commented on lawlibrary/views/home.py
> +        context["recent_articles"] = Article.objects.order_by("-date")[:5]
For now, only africanlii has any need of articles, so this and the changes to home.html and header.html can go into africanlii.

2022-09-26 11:17 UTC, longhotsummer commented on peachjam/views/article.py
> +    model = Article
Queryset should filter on published articles, otherwise draft articles will be visible.

2022-09-26 11:17 UTC, longhotsummer commented on peachjam/views/article.py
> +    model = Article
Queryset must filter on published articles only.

2022-09-26 11:17 UTC, longhotsummer commented on peachjam/views/article.py
> +        print(self.__dict__)
remove

2022-09-26 11:17 UTC, longhotsummer commented on peachjam/templates/peachjam/article_detail.html
> +
fix indents, pls

2022-09-26 11:18 UTC, longhotsummer requested changes
Draft articles shouldn't be visible.

Please also add a loom or screenshots showing what this looks like in the listing and detail views.

What's the admin experience like for creating a new article?

2022-09-30 12:15 UTC, longhotsummer approved these changes

2022-09-30 12:49 UTC, merged