As a user clicking through to a search result, I want the search to be carried through
laws-africa/peachjam pull request #445
Opened 2022-09-20 18:37 UTC by Sandravaphilips

- Issue: https://github.com/laws-africa/peachjam/issues/352

2022-09-21 09:53 UTC, musangowope commented on peachjam/js/components/FindDocuments/SearchResult.vue
> +      :href="`${item.expression_frbr_uri}?q=${query}`"
wrap `q` in `encodeURIComponent`

2022-09-21 09:56 UTC, musangowope commented on peachjam/js/components/FindDocuments/SearchResult.vue
> +      :href="`${item.expression_frbr_uri}?q=${query}`"
wrap `query` with `encodeURIComponent`

2022-09-21 10:04 UTC, musangowope requested changes
Great first step. The next step would be to accomodate pdf documents. You need to trigger the search only once the pdf document has loaded

2022-09-21 10:13 UTC, musangowope commented
Taking videos of work done for prs can also be really valuable. We like to use a tool called [Loom](https://www.loom.com/)

2022-09-23 15:19 UTC, musangowope commented on peachjam/js/components/document-content.ts
> +          searchInput.value = 'law';
this is a hard-coded value. I'm guessing you were using this for testing purposes. Please set `search.value` to the  `url param` `q`

2022-09-23 15:20 UTC, musangowope requested changes
Minor change

2022-09-23 15:24 UTC, musangowope commented
it would also be amazing if we could immediately activate the search tab in `in-document search` if  url param `q` exists

2022-09-26 12:29 UTC, longhotsummer commented
> it would also be amazing if we could immediately activate the search tab in `in-document search` if url param `q` exists

Yes please!

2022-09-27 08:22 UTC, musangowope approved these changes

2022-09-28 07:54 UTC, merged