Filter search results by judge
laws-africa/peachjam pull request #799
Opened 2023-01-11 13:51 UTC by nickmwangemi

2023-01-11 15:39 UTC, actlikewill commented on peachjam/js/components/FindDocuments/index.vue
> +      {{ $t('Judges') }}
@nickmwangemi are we supposed to remove year here?

2023-01-12 05:58 UTC, longhotsummer requested changes
Looks great.

I think it would be better if the judges facet comes just below the Court facet. The Court and Judge are closely logically linked.

2023-01-12 06:30 UTC, nickmwangemi commented
> Looks great.
> 
> I think it would be better if the judges facet comes just below the Court facet. The Court and Judge are closely logically linked.

I've made the change:
![image](https://user-images.githubusercontent.com/15012985/211993980-2857953a-dc36-448d-8f37-7c54a16f6eaf.png)

2023-01-16 06:30 UTC, longhotsummer commented
Looks good. I'll wait for #805 to be merged before approving, then we can deploy both.

2023-01-16 07:34 UTC, longhotsummer approved these changes

2023-01-16 08:23 UTC, merged