The great migration
laws-africa/peachjam pull request #880
Opened 2023-01-27 11:12 UTC by nickmwangemi

2023-01-31 04:50 UTC, actlikewill commented
@nickmwangemi I can see some crocodiles are attacking the herd as they cross the river :laughing:

2023-01-31 04:54 UTC, nickmwangemi commented
> @nickmwangemi I can see some crocodiles are attacking the herd as they cross the river laughing

Still a WIP

2023-02-02 06:22 UTC, longhotsummer commented on sierralii/static/images/banner.jpg
> +/home/nickmwangemi/Downloads/banner.jpg
Looks like a symlink :)

2023-02-02 06:26 UTC, longhotsummer requested changes
Nice!

* The sierralii banner image needs to be added
* the lawlibrary.org.za banner image isn't showing up (i think it needs to be renamed)

2023-02-02 09:00 UTC, actlikewill commented on sierralii/static/images/banner.jpg
> +/home/nickmwangemi/Downloads/banner.jpg
@longhotsummer Changed

2023-02-02 09:54 UTC, longhotsummer submitted a review, later dismissed

2023-02-02 14:44 UTC, merged