Tweak gazettes on agp
laws-africa/peachjam pull request #939
Opened 2023-02-16 14:19 UTC by nickmwangemi

This PR tweaks how gazettes are displayed on AGP. 

Before:
![image](https://user-images.githubusercontent.com/15012985/219389173-933086ab-798f-4c19-82b6-27a145a4053a.png)

![image](https://user-images.githubusercontent.com/15012985/219389386-444f301d-b7f0-4cbe-af21-3e01f36d36bc.png)

![image](https://user-images.githubusercontent.com/15012985/219389724-0ad66e81-f770-477f-8ce1-be419974e704.png)

After:
![image](https://user-images.githubusercontent.com/15012985/219389280-425e7dae-a1fd-41da-af6f-76c0cbf459e3.png)

https://www.loom.com/share/32a808bce9884d5b98eddd18408eee52

2023-02-16 14:51 UTC, longhotsummer commented on peachjam/views/gazette.py
> +        gazettes = queryset.filter(locality__in=localities)
Consider this in context. When viewing South Africa, this loads 60,000 gazettes and iterates over all of them, just to add 9 localities to the set. It's very inefficient. It's also going to be doing it on a page where locality is set, even though it's never used.

Here's a better query:

```
>>> str(qs.order_by().distinct("locality").values_list("locality", flat=True).query)
'SELECT DISTINCT ON ("peachjam_coredocument"."locality_id") "peachjam_coredocument"."locality_id" FROM "peachjam_gazette" INNER JOIN "peachjam_coredocument" ON ("peachjam_gazette"."coredocument_ptr_id" = "peachjam_coredocument"."id")'
>>> list(qs.order_by().distinct("locality").values_list("locality", flat=True))
[6, None]
```

So instead,

1. only calculate this when `self.locality` is None
2. use this to get distinct locality ids: `list(qs.order_by().distinct("locality").values_list("locality", flat=True))`

2023-02-16 14:53 UTC, longhotsummer requested changes
Nice!

Some query changes, please.

Are the specialised LawLibraryGazette* views still necessary after this?

2023-02-17 07:47 UTC, nickmwangemi commented
> Nice!
> 
> Some query changes, please.
> 
> Are the specialised LawLibraryGazette* views still necessary after this?

The LawLibrary-specific views can fall off

2023-02-17 08:22 UTC, longhotsummer commented on lawlibrary/templates/peachjam/gazette_detail.html
>      <ol class="breadcrumb">
this file is now identical to peachjam's gazette_detail so the lawlibrary one can fall away

2023-02-17 10:00 UTC, merged